const { sendHtmlApp } = require('../lib/htmlTransport');

function buildPhoneHtml() {
  // Built without nested template traps; apostrophes avoided in JS strings
  return [
'<!DOCTYPE html><html><head><meta charset="utf-8"/>',
'<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"/>',
'<style>',
'*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;user-select:none;margin:0;padding:0}',
'html,body{height:100%;font-family:system-ui,-apple-system,sans-serif;background:#020617;color:#f8fafc;overflow:hidden}',
'.phone{max-width:400px;margin:0 auto;height:100%;display:flex;flex-direction:column;',
'background:linear-gradient(165deg,#1e1b4b 0%,#0f172a 55%,#020617 100%)}',
'.sb{display:flex;justify-content:space-between;padding:10px 14px 4px;font-size:12px;font-weight:700}',
'.widget{margin:8px 12px;padding:14px;border-radius:18px;background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.12)}',
'.clk{font-size:40px;font-weight:200;letter-spacing:1px}.sub{font-size:12px;color:#94a3b8;margin-top:4px}',
'.pages{flex:1;display:flex;overflow-x:auto;scroll-snap-type:x mandatory;-webkit-overflow-scrolling:touch}',
'.pages::-webkit-scrollbar{display:none}',
'.page{min-width:100%;scroll-snap-align:start;padding:8px 10px;display:grid;grid-template-columns:repeat(4,1fr);gap:12px 6px;align-content:start}',
'.ic{text-align:center;cursor:pointer}.ic .b{width:50px;height:50px;margin:0 auto;border-radius:14px;display:flex;align-items:center;justify-content:center;font-size:22px;box-shadow:0 4px 12px rgba(0,0,0,.3)}',
'.ic .b:active{transform:scale(.92)}.ic span{display:block;font-size:9px;margin-top:4px;font-weight:600;color:#e2e8f0}',
'.dots{display:flex;justify-content:center;gap:5px;padding:6px}.dots i{width:6px;height:6px;border-radius:50%;background:rgba(255,255,255,.25)}.dots i.on{width:14px;border-radius:4px;background:#fff}',
'.dock{margin:4px 12px 12px;padding:10px;border-radius:22px;background:rgba(255,255,255,.12);display:flex;justify-content:space-around;border:1px solid rgba(255,255,255,.1)}',
'.app{position:absolute;inset:0;background:#0f172a;z-index:40;display:none;flex-direction:column}.app.on{display:flex}',
'.ah{display:flex;align-items:center;gap:8px;padding:10px 12px;background:#1e293b;border-bottom:1px solid rgba(255,255,255,.06)}',
'.ah button{background:none;border:0;color:#38bdf8;font-weight:700;font-size:15px}',
'.ah h3{margin:0;font-size:14px;flex:1}',
'.ab{flex:1;overflow:auto;padding:12px;font-size:13px}',
'input,textarea,select{width:100%;padding:10px;border-radius:10px;border:1px solid rgba(255,255,255,.12);background:#1e293b;color:#f1f5f9;margin:4px 0 8px;font-size:14px}',
'button.p{width:100%;padding:11px;border:0;border-radius:12px;background:#3b82f6;color:#fff;font-weight:700;margin-top:4px}',
'button.p.sec{background:#334155}.out{background:#020617;border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:10px;margin-top:8px;white-space:pre-wrap;word-break:break-word;min-height:36px}',
'.row{display:flex;gap:6px}.row>*{flex:1}',
'.pad{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.pad button{padding:14px 0;border:0;border-radius:12px;background:#1e293b;color:#fff;font-size:16px;font-weight:600}',
'.pad button.op{background:#334155;color:#fbbf24}.pad button.eq{background:#3b82f6}',
'.disp{background:#020617;border-radius:12px;padding:14px;font-size:26px;text-align:right;margin-bottom:8px;min-height:48px}',
'</style></head><body><div class="phone">',
'<div class="sb"><span id="sbT">00:00</span><span>MiniOS</span></div>',
'<div class="home" id="home" style="flex:1;display:flex;flex-direction:column;min-height:0;position:relative">',
'<div class="widget"><div class="clk" id="bigT">00:00</div><div class="sub" id="bigD">—</div></div>',
'<div class="pages" id="pages"><div class="page" id="p0"></div><div class="page" id="p1"></div><div class="page" id="p2"></div></div>',
'<div class="dots"><i class="on" id="d0"></i><i id="d1"></i><i id="d2"></i></div>',
'<div class="dock" id="dock"></div></div>',
'<div class="app" id="av"><div class="ah"><button type="button" id="bk">Back</button><h3 id="at">App</h3></div><div class="ab" id="ab"></div></div>',
'</div><script>',
'(function(){',
'var APPS=[',
'{id:"calc",n:"Calc",e:"1",c:"#0ea5e9",p:0},',
'{id:"notes",n:"Notes",e:"N",c:"#eab308",p:0},',
'{id:"todo",n:"Tasks",e:"T",c:"#22c55e",p:0},',
'{id:"timer",n:"Timer",e:"tm",c:"#f97316",p:0},',
'{id:"stop",n:"Stopwatch",e:"sw",c:"#a855f7",p:0},',
'{id:"focus",n:"Focus",e:"F",c:"#8b5cf6",p:0},',
'{id:"dice",n:"Dice",e:"D",c:"#ef4444",p:0},',
'{id:"coin",n:"Coin",e:"C",c:"#f59e0b",p:0},',
'{id:"bmi",n:"BMI",e:"B",c:"#14b8a6",p:1},',
'{id:"age",n:"Age",e:"A",c:"#ec4899",p:1},',
'{id:"unit",n:"Units",e:"U",c:"#06b6d4",p:1},',
'{id:"fx",n:"FX",e:"$",c:"#84cc16",p:1},',
'{id:"emi",n:"EMI",e:"E",c:"#8b5cf6",p:1},',
'{id:"pass",n:"Password",e:"P",c:"#64748b",p:1},',
'{id:"rand",n:"Random",e:"R",c:"#f43f5e",p:1},',
'{id:"word",n:"Words",e:"W",c:"#3b82f6",p:1},',
'{id:"ball",n:"8Ball",e:"8",c:"#1e293b",p:2},',
'{id:"spin",n:"Spin",e:"S",c:"#db2777",p:2},',
'{id:"rps",n:"RPS",e:"X",c:"#6366f1",p:2},',
'{id:"count",n:"Counter",e:"+",c:"#0ea5e9",p:2},',
'{id:"world",n:"Clocks",e:"G",c:"#059669",p:2},',
'{id:"color",n:"Color",e:"O",c:"#e11d48",p:2},',
'{id:"fuel",n:"Fuel",e:"L",c:"#ea580c",p:2},',
'{id:"about",n:"About",e:"i",c:"#475569",p:2}',
'];',
'var DOCK=["calc","notes","todo","focus"];',
'function tick(){var d=new Date();var t=d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});',
'document.getElementById("sbT").textContent=t;document.getElementById("bigT").textContent=t;',
'document.getElementById("bigD").textContent=d.toLocaleDateString([],{weekday:"long",month:"short",day:"numeric"});}',
'setInterval(tick,1000);tick();',
'function icon(a){var el=document.createElement("div");el.className="ic";',
'el.innerHTML="<div class=\\"b\\" style=\\"background:"+a.c+"\\">"+a.e+"</div><span>"+a.n+"</span>";',
'el.onclick=function(){openApp(a.id)};return el;}',
'APPS.forEach(function(a){var pg=document.getElementById("p"+a.p);if(pg)pg.appendChild(icon(a));});',
'DOCK.forEach(function(id){var a=APPS.find(function(x){return x.id===id});if(a)document.getElementById("dock").appendChild(icon(a));});',
'var pages=document.getElementById("pages");',
'pages.onscroll=function(){var i=Math.round(pages.scrollLeft/pages.clientWidth);[0,1,2].forEach(function(n){var d=document.getElementById("d"+n);if(d)d.className=n===i?"on":"";});};',
'function openApp(id){var a=APPS.find(function(x){return x.id===id});if(!a)return;',
'document.getElementById("at").textContent=a.n;document.getElementById("ab").innerHTML="";',
'document.getElementById("av").classList.add("on");if(UI[id])UI[id](document.getElementById("ab"));}',
'document.getElementById("bk").onclick=function(){document.getElementById("av").classList.remove("on");};',
'var UI={',
'calc:function(el){el.innerHTML="<div class=\\"disp\\" id=\\"cd\\">0</div><div class=\\"pad\\" id=\\"cp\\"></div>";',
'var cur="0",op=null,prev=null;var keys=["C","B","%","/","7","8","9","*","4","5","6","-","1","2","3","+","0",".","N","="];',
'keys.forEach(function(k){var b=document.createElement("button");b.textContent=k==="B"?"<":(k==="N"?"+/-":k);',
'if("/*%-+".indexOf(k)>=0)b.className="op";if(k==="=")b.className="eq";',
'b.onclick=function(){if(k==="C"){cur="0";op=null;prev=null;}else if(k==="B"){cur=cur.length>1?cur.slice(0,-1):"0";}',
'else if(k==="N"){cur=String(-(+cur));}else if(k==="%"){cur=String(+cur/100);}',
'else if("/*-+".indexOf(k)>=0){prev=+cur;op=k;cur="0";}else if(k==="="){var n=+cur;',
'if(op==="+")cur=String(prev+n);if(op==="-")cur=String(prev-n);if(op==="*")cur=String(prev*n);if(op==="/")cur=String(n?prev/n:"Err");op=null;}',
'else{if(k==="."&&cur.indexOf(".")>=0)return;cur=(cur==="0"&&k!==".")?k:cur+k;}document.getElementById("cd").textContent=cur;};',
'document.getElementById("cp").appendChild(b);});},',
'notes:function(el){var k="mb_notes";el.innerHTML="<textarea id=\\"nt\\" rows=\\"10\\">"+ (localStorage.getItem(k)||"") +"</textarea><button class=\\"p\\" id=\\"sv\\">Save</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("sv").onclick=function(){localStorage.setItem(k,document.getElementById("nt").value);document.getElementById("o").textContent="Saved";};},',
'todo:function(el){var k="mb_todo";var items=[];try{items=JSON.parse(localStorage.getItem(k)||"[]");}catch(e){items=[];}',
'function ren(){el.innerHTML="<div class=\\"row\\"><input id=\\"ti\\" placeholder=\\"New task\\"/><button class=\\"p\\" id=\\"ad\\" style=\\"flex:0 0 64px\\">Add</button></div><div id=\\"ul\\"></div>";',
'items.forEach(function(it,i){var d=document.createElement("div");d.className="out";d.textContent=(it.d?"[x] ":"[ ] ")+it.t;',
'd.onclick=function(){it.d=!it.d;localStorage.setItem(k,JSON.stringify(items));ren();};document.getElementById("ul").appendChild(d);});',
'document.getElementById("ad").onclick=function(){var v=document.getElementById("ti").value.trim();if(!v)return;items.push({t:v,d:0});localStorage.setItem(k,JSON.stringify(items));ren();};}',
'ren();},',
'timer:function(el){el.innerHTML="<label>Minutes</label><input id=\\"m\\" type=\\"number\\" value=\\"5\\"/><button class=\\"p\\" id=\\"st\\">Start</button><div class=\\"out\\" id=\\"o\\" style=\\"font-size:28px;text-align:center\\">05:00</div>";',
'var t=null,left=300;document.getElementById("st").onclick=function(){if(t){clearInterval(t);t=null;document.getElementById("st").textContent="Start";return;}',
'left=Math.max(1,+(document.getElementById("m").value)||5)*60;document.getElementById("st").textContent="Stop";',
't=setInterval(function(){left--;var mm=String(Math.floor(left/60)).padStart(2,"0");var ss=String(left%60).padStart(2,"0");',
'document.getElementById("o").textContent=mm+":"+ss;if(left<=0){clearInterval(t);t=null;document.getElementById("o").textContent="Done";document.getElementById("st").textContent="Start";}},1000);};},',
'stop:function(el){el.innerHTML="<div class=\\"out\\" id=\\"o\\" style=\\"font-size:28px;text-align:center\\">00:00.0</div><div class=\\"row\\"><button class=\\"p\\" id=\\"st\\">Start</button><button class=\\"p sec\\" id=\\"rs\\">Reset</button></div>";',
'var t=null,ms=0;document.getElementById("st").onclick=function(){if(t){clearInterval(t);t=null;document.getElementById("st").textContent="Start";return;}',
'document.getElementById("st").textContent="Stop";var t0=Date.now()-ms;t=setInterval(function(){ms=Date.now()-t0;var s=Math.floor(ms/1000),m=Math.floor(s/60);',
'document.getElementById("o").textContent=String(m).padStart(2,"0")+":"+String(s%60).padStart(2,"0")+"."+Math.floor((ms%1000)/100);},100);};',
'document.getElementById("rs").onclick=function(){clearInterval(t);t=null;ms=0;document.getElementById("o").textContent="00:00.0";document.getElementById("st").textContent="Start";};},',
'focus:function(el){var left=25*60,t=null;el.innerHTML="<div class=\\"out\\" id=\\"o\\" style=\\"font-size:32px;text-align:center\\">25:00</div><div class=\\"row\\"><button class=\\"p\\" id=\\"st\\">Start</button><button class=\\"p sec\\" id=\\"rs\\">Reset</button></div>";',
'function show(){document.getElementById("o").textContent=String(Math.floor(left/60)).padStart(2,"0")+":"+String(left%60).padStart(2,"0");}',
'document.getElementById("st").onclick=function(){if(t){clearInterval(t);t=null;document.getElementById("st").textContent="Start";return;}document.getElementById("st").textContent="Pause";',
't=setInterval(function(){left--;show();if(left<=0){clearInterval(t);t=null;document.getElementById("o").textContent="Break";document.getElementById("st").textContent="Start";}},1000);};',
'document.getElementById("rs").onclick=function(){clearInterval(t);t=null;left=25*60;show();document.getElementById("st").textContent="Start";};show();},',
'dice:function(el){el.innerHTML="<div class=\\"out\\" id=\\"o\\" style=\\"font-size:36px;text-align:center\\">?</div><button class=\\"p\\" id=\\"g\\">Roll</button>";',
'document.getElementById("g").onclick=function(){document.getElementById("o").textContent=String(1+Math.floor(Math.random()*6));};},',
'coin:function(el){el.innerHTML="<div class=\\"out\\" id=\\"o\\" style=\\"font-size:28px;text-align:center\\">?</div><button class=\\"p\\" id=\\"g\\">Flip</button>";',
'document.getElementById("g").onclick=function(){document.getElementById("o").textContent=Math.random()<0.5?"Heads":"Tails";};},',
'bmi:function(el){el.innerHTML="<label>Height cm</label><input id=\\"h\\" type=\\"number\\" value=\\"170\\"/><label>Weight kg</label><input id=\\"w\\" type=\\"number\\" value=\\"65\\"/><button class=\\"p\\" id=\\"g\\">Calc</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("g").onclick=function(){var m=+(document.getElementById("h").value)/100;var b=(+(document.getElementById("w").value))/(m*m);var c="Normal";if(b<18.5)c="Underweight";else if(b>=25&&b<30)c="Overweight";else if(b>=30)c="Obese";document.getElementById("o").textContent="BMI "+b.toFixed(1)+"\\n"+c;};},',
'age:function(el){el.innerHTML="<label>Birth date</label><input id=\\"d\\" type=\\"date\\"/><button class=\\"p\\" id=\\"g\\">Age</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("g").onclick=function(){var v=document.getElementById("d").value;if(!v)return;var b=new Date(v),n=new Date();var y=n.getFullYear()-b.getFullYear();document.getElementById("o").textContent=y+" years approx";};},',
'unit:function(el){el.innerHTML="<label>Value</label><input id=\\"v\\" type=\\"number\\" value=\\"10\\"/><select id=\\"t\\"><option value=\\"1\\">km to mi</option><option value=\\"2\\">mi to km</option><option value=\\"3\\">kg to lb</option><option value=\\"4\\">C to F</option></select><button class=\\"p\\" id=\\"g\\">Go</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("g").onclick=function(){var v=+(document.getElementById("v").value),t=document.getElementById("t").value;var r=t=="1"?v*0.621:t=="2"?v*1.609:t=="3"?v*2.205:v*9/5+32;document.getElementById("o").textContent=r.toFixed(3);};},',
'fx:function(el){el.innerHTML="<label>PKR</label><input id=\\"a\\" type=\\"number\\" value=\\"1000\\"/><button class=\\"p\\" id=\\"g\\">Convert</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("g").onclick=function(){var p=+(document.getElementById("a").value);document.getElementById("o").textContent="USD ~"+(p/278).toFixed(2)+"\\nEUR ~"+(p/300).toFixed(2)+"\\nAED ~"+(p/75.7).toFixed(2);};},',
'emi:function(el){el.innerHTML="<label>Loan</label><input id=\\"p\\" type=\\"number\\" value=\\"500000\\"/><label>Rate %/yr</label><input id=\\"r\\" type=\\"number\\" value=\\"14\\"/><label>Months</label><input id=\\"n\\" type=\\"number\\" value=\\"36\\"/><button class=\\"p\\" id=\\"g\\">EMI</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("g").onclick=function(){var P=+(document.getElementById("p").value),R=+(document.getElementById("r").value)/12/100,N=+(document.getElementById("n").value);var e=P*R*Math.pow(1+R,N)/(Math.pow(1+R,N)-1);document.getElementById("o").textContent="Monthly "+e.toFixed(0)+"\\nTotal "+(e*N).toFixed(0);};},',
'pass:function(el){el.innerHTML="<label>Length</label><input id=\\"l\\" type=\\"number\\" value=\\"16\\"/><button class=\\"p\\" id=\\"g\\">Generate</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("g").onclick=function(){var c="abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$",n=+(document.getElementById("l").value)||16,s="";for(var i=0;i<n;i++)s+=c[Math.floor(Math.random()*c.length)];document.getElementById("o").textContent=s;};},',
'rand:function(el){el.innerHTML="<label>Min</label><input id=\\"a\\" type=\\"number\\" value=\\"1\\"/><label>Max</label><input id=\\"b\\" type=\\"number\\" value=\\"100\\"/><button class=\\"p\\" id=\\"g\\">Pick</button><div class=\\"out\\" id=\\"o\\" style=\\"font-size:28px;text-align:center\\"></div>";',
'document.getElementById("g").onclick=function(){var lo=+(document.getElementById("a").value),hi=+(document.getElementById("b").value);document.getElementById("o").textContent=String(Math.floor(Math.random()*(hi-lo+1))+lo);};},',
'word:function(el){el.innerHTML="<textarea id=\\"t\\" rows=\\"6\\"></textarea><button class=\\"p\\" id=\\"g\\">Count</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("g").onclick=function(){var s=document.getElementById("t").value;var w=s.trim()?s.trim().split(/\\s+/).length:0;document.getElementById("o").textContent="Chars "+s.length+"\\nWords "+w;};},',
'ball:function(el){var a=["Yes","No","Maybe","Ask again","Definitely","Doubtful","Absolutely","Not now"];',
'el.innerHTML="<input id=\\"q\\" placeholder=\\"Question\\"/><button class=\\"p\\" id=\\"g\\">Shake</button><div class=\\"out\\" id=\\"o\\" style=\\"text-align:center;font-size:18px\\"></div>";',
'document.getElementById("g").onclick=function(){document.getElementById("o").textContent=a[Math.floor(Math.random()*a.length)];};},',
'spin:function(el){el.innerHTML="<label>Options (comma)</label><input id=\\"o\\" value=\\"A, B, C, D\\"/><button class=\\"p\\" id=\\"g\\">Spin</button><div class=\\"out\\" id=\\"r\\" style=\\"font-size:22px;text-align:center\\"></div>";',
'document.getElementById("g").onclick=function(){var p=document.getElementById("o").value.split(",").map(function(s){return s.trim()}).filter(Boolean);document.getElementById("r").textContent=p.length?p[Math.floor(Math.random()*p.length)]:"?";};},',
'rps:function(el){el.innerHTML="<div class=\\"row\\"><button class=\\"p\\" data-m=\\"rock\\">Rock</button><button class=\\"p\\" data-m=\\"paper\\">Paper</button><button class=\\"p\\" data-m=\\"scissors\\">Scissors</button></div><div class=\\"out\\" id=\\"o\\"></div>";',
'el.querySelectorAll("[data-m]").forEach(function(b){b.onclick=function(){var you=b.getAttribute("data-m");var ai=["rock","paper","scissors"][Math.floor(Math.random()*3)];',
'var r="Draw";if((you==="rock"&&ai==="scissors")||(you==="paper"&&ai==="rock")||(you==="scissors"&&ai==="paper"))r="You win";else if(you!==ai)r="You lose";',
'document.getElementById("o").textContent="You: "+you+"\\nBot: "+ai+"\\n"+r;};});},',
'count:function(el){var n=0;el.innerHTML="<div class=\\"out\\" id=\\"o\\" style=\\"font-size:36px;text-align:center\\">0</div><div class=\\"row\\"><button class=\\"p\\" id=\\"m\\">-</button><button class=\\"p\\" id=\\"p\\">+</button></div>";',
'document.getElementById("m").onclick=function(){n--;document.getElementById("o").textContent=n;};document.getElementById("p").onclick=function(){n++;document.getElementById("o").textContent=n;};},',
'world:function(el){var zs=[["Pakistan","Asia/Karachi"],["London","Europe/London"],["New York","America/New_York"],["Dubai","Asia/Dubai"]];',
'function ren(){el.innerHTML=zs.map(function(z){return "<div class=\\"out\\" style=\\"display:flex;justify-content:space-between\\"><span>"+z[0]+"</span><b>"+new Date().toLocaleTimeString([],{timeZone:z[1],hour:"2-digit",minute:"2-digit"})+"</b></div>";}).join("");}',
'ren();setInterval(ren,1000);},',
'color:function(el){el.innerHTML="<input id=\\"c\\" type=\\"color\\" value=\\"#3b82f6\\" style=\\"height:48px;padding:0\\"/><div class=\\"out\\" id=\\"o\\"></div>";',
'function up(){document.getElementById("o").textContent=document.getElementById("c").value;}document.getElementById("c").oninput=up;up();},',
'fuel:function(el){el.innerHTML="<label>Distance km</label><input id=\\"d\\" type=\\"number\\" value=\\"100\\"/><label>Km per liter</label><input id=\\"k\\" type=\\"number\\" value=\\"12\\"/><label>Price / L</label><input id=\\"p\\" type=\\"number\\" value=\\"280\\"/><button class=\\"p\\" id=\\"g\\">Cost</button><div class=\\"out\\" id=\\"o\\"></div>";',
'document.getElementById("g").onclick=function(){var lit=(+(document.getElementById("d").value))/(+(document.getElementById("k").value)||1);document.getElementById("o").textContent="Fuel "+lit.toFixed(2)+" L\\nCost "+(lit*(+(document.getElementById("p").value))).toFixed(0);};},',
'about:function(el){el.innerHTML="<div class=\\"out\\"><b>MiniOS Phone</b>\\nSwipe pages for apps\\nAll offline inside WhatsApp\\nMiniBot</div>";}',
'};',
'})();',
'</script></body></html>'
  ].join('');
}

module.exports = {
  name: 'phone',
  pattern: 'phone',
  aliases: ['mobile', 'launcher', 'os', 'home'],
  desc: 'Smartphone launcher',
  category: 'apps',
  async handler({ sock, jid }) {
    await sendHtmlApp(sock, jid, buildPhoneHtml(), 'Phone');
  },
};
